"""Milestone 3 — geometry generated by us, not copied from Goodnotes.

Two strokes are built from scratch and encoded as PConstantWidthStroke, the family whose
every member we have solved. An existing record supplies only the container fields whose
semantics we have not reproduced (descriptor constants, item fields 3/6/7/9/20/21).

The original sample strokes are left in place as a visual reference.
"""
import os
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from inkref.goodnotes import strokes as strokes_mod                      # noqa: E402
from inkref.goodnotes.document import Document, Stroke, to_points   # noqa: E402

SOURCE = os.path.join(ROOT, "samples", "test.goodnotes")
OUTPUT = os.path.join(ROOT, "generated", "03_synthetic_stroke.goodnotes")

BLUE = (0.10, 0.35, 0.90, 1.0)
RED = (0.85, 0.15, 0.15, 1.0)

# exactly the path from the brief
LINE = [(100.0, 100.0), (120.0, 100.0), (140.0, 100.0), (160.0, 100.0)]
# a multi-segment path, so the test is not only a straight line
ZIGZAG = [(100.0 + 40 * i, 220.0 + (60.0 if i % 2 else 0.0)) for i in range(9)]

SYNTHETIC = [
    ("line", Stroke(points=LINE, color=BLUE, width=6.0)),
    ("zigzag", Stroke(points=ZIGZAG, color=RED, width=6.0)),
]


def main():
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

    doc = Document.open(SOURCE)
    page = next(p for p in doc.pages if p.records)
    existing = {r.uuid for r in page.records}
    existing_bounds = {r.uuid: strokes_mod.bounds(*r.geometry) for r in page.records}

    print(f"source   : {os.path.relpath(SOURCE, ROOT)}  schema={doc.schema}")
    print(f"page     : {page.id}")
    print(f"template : {len(existing)} existing record(s) supply undecoded container fields")

    made = []
    for name, stroke in SYNTHETIC:
        rec = doc.add_stroke(page.id, stroke)
        made.append((name, stroke, rec))
        print(f"added    : {name:7s} {rec.uuid}  {len(stroke.points)} pts  "
              f"width={stroke.width}u ({to_points(stroke.width):.2f}pt)")

    doc.write(OUTPUT)

    # ---- verify ----
    check = Document.open(OUTPUT)
    out_page = check.pages[[p.id for p in check.pages].index(page.id)]
    assert len(out_page.records) == len(existing) + len(SYNTHETIC)

    by_uuid = {r.uuid: r for r in out_page.records}

    # originals untouched
    for uuid, bounds in existing_bounds.items():
        got = strokes_mod.bounds(*by_uuid[uuid].geometry)
        assert got == bounds or (got is None and bounds is None), f"{uuid} changed"

    for name, stroke, rec in made:
        got = by_uuid[rec.uuid]
        sig, members = got.geometry

        # right family, and the geometry is ours
        assert sig == strokes_mod.CONSTANT_WIDTH, sig
        pts = strokes_mod.on_curve_points(sig, members)
        assert len(pts) == len(stroke.points), (name, len(pts), len(stroke.points))
        for (ax, ay), (bx, by) in zip(stroke.points, pts):
            assert abs(ax - bx) < 1e-3 and abs(ay - by) < 1e-3, (name, ax, ay, bx, by)

        # opcodes: one moveTo then a quadCurveTo per segment
        assert members[2] == [strokes_mod.MOVE_TO] + \
            [strokes_mod.QUAD_TO] * (len(stroke.points) - 1), (name, members[2])

        # width, colour, identity, pairing
        _, width = strokes_mod.svg_path(sig, members)
        assert abs(width - stroke.width) < 1e-4, (name, width)
        assert all(abs(a - b) < 1e-6 for a, b in zip(got.color, stroke.color)), got.color
        assert got.uuid not in existing
        assert got.is_consistent(), f"{name}: descriptor/item mismatch"
        # a new record must never inherit a tombstone marker from its template
        assert not got.deleted, f"{name}: born deleted — it would import but never render"

    uuids = [r.uuid for r in out_page.records]
    assert len(set(uuids)) == len(uuids), "duplicate uuid"
    versions = [r.version for r in out_page.records]
    assert len(set(versions)) == len(versions), "duplicate version stamp"

    zin, zout = zipfile.ZipFile(SOURCE), zipfile.ZipFile(OUTPUT)
    assert zin.namelist() == zout.namelist()
    changed = [n for n in zin.namelist() if zin.read(n) != zout.read(n)]
    assert changed == [page.path], f"unexpected members changed: {changed}"

    print(f"family   : {strokes_mod.CONSTANT_WIDTH}")
    print(f"geometry : decodes back to the exact input points on both strokes")
    print(f"records  : {len(existing)} -> {len(out_page.records)}; all uuids and "
          f"version stamps distinct")
    print(f"invariant: descriptor.f2 == item.f15 holds for all records")
    print(f"originals: untouched")
    print(f"zip      : only {page.path} differs")
    print(f"wrote    : {os.path.relpath(OUTPUT, ROOT)}")


if __name__ == "__main__":
    main()
