"""Milestone 5 — PDF -> InkDocument -> .goodnotes, checked against known ground truth.

    .goodnotes (authored by us, geometry known exactly)
      -> exported from Goodnotes as an Editable PDF
        -> extracted here
          -> written back to .goodnotes

Because the source notebook was generated by milestone 3, the authored coordinates are known
to the last float, so extraction accuracy is measured numerically rather than by eye.

Run:  ./venv/bin/python milestones/m5_pdf_roundtrip.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from inkport.goodnotes.document import POINTS_PER_UNIT      # noqa: E402
from inkport.goodnotes.writer import GoodNotesWriter, reader_to_ink  # noqa: E402
from inkport.pdf import extract as pdf_extract              # noqa: E402

PDF = os.path.join(ROOT, "samples", "pdf", "03c_synthetic_stroke.pdf")
ORIGINAL = os.path.join(ROOT, "generated", "03_synthetic_stroke.goodnotes")
TEMPLATE = os.path.join(ROOT, "samples", "test.goodnotes")
OUTPUT = os.path.join(ROOT, "generated", "05_from_pdf.goodnotes")

# The geometry milestone 3 authored, in GoodNotes units
AUTHORED = {
    "line": [(100.0, 100.0), (120.0, 100.0), (140.0, 100.0), (160.0, 100.0)],
    "zigzag": [(100.0 + 40 * i, 220.0 + (60.0 if i % 2 else 0.0)) for i in range(9)],
}


def bbox(points):
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return (min(xs), min(ys), max(xs), max(ys))


def main():
    if not os.path.exists(PDF):
        sys.exit(f"missing {PDF} — export the notebook from Goodnotes as an Editable PDF")

    ink = pdf_extract.extract(PDF)
    page = ink.pages[0]
    print(f"pdf        : {os.path.relpath(PDF, ROOT)}")
    print(f"page       : {page.width:.1f} x {page.height:.1f} pt")
    print(f"extracted  : {len(page)} strokes\n")

    # --- accuracy against the authored geometry -------------------------------------
    print("accuracy vs authored geometry (converted to points):")
    for name, units in AUTHORED.items():
        want = [(x * POINTS_PER_UNIT, y * POINTS_PER_UNIT) for x, y in units]
        wx0, wy0, wx1, wy1 = bbox(want)
        # match by bounding box overlap — colour is the practical discriminator but the
        # bbox is what actually matters for placement
        best, best_err = None, 1e9
        for s in page.strokes:
            gx0, gy0, gx1, gy1 = s.bounds
            err = abs(gx0 - wx0) + abs(gy0 - wy0) + abs(gx1 - wx1) + abs(gy1 - wy1)
            if err < best_err:
                best, best_err = s, err
        gx0, gy0, gx1, gy1 = best.bounds
        print(f"  {name:7s} authored bbox ({wx0:7.2f},{wy0:7.2f})-({wx1:7.2f},{wy1:7.2f})")
        print(f"          extracted     ({gx0:7.2f},{gy0:7.2f})-({gx1:7.2f},{gy1:7.2f})  "
              f"max err {max(abs(gx0-wx0), abs(gy0-wy0), abs(gx1-wx1), abs(gy1-wy1)):.2f} pt")
        print(f"          {len(units)} authored pts -> {len(best.points)} extracted  "
              f"colour #{int(best.color.r*255):02x}{int(best.color.g*255):02x}"
              f"{int(best.color.b*255):02x}  width {best.width:.2f} pt")

    # --- colour fidelity against the original archive --------------------------------
    orig = reader_to_ink(ORIGINAL)
    orig_colors = {tuple(round(c, 2) for c in s.color.as_tuple()) for p in orig.pages
                   for s in p.strokes}
    got_colors = {tuple(round(c, 2) for c in s.color.as_tuple()) for s in page.strokes}
    shared = orig_colors & got_colors
    print(f"\ncolours    : {len(shared)}/{len(orig_colors)} of the original colours "
          f"survived the PDF round trip")

    # --- write it back ---------------------------------------------------------------
    out, written = GoodNotesWriter(TEMPLATE).write(ink, OUTPUT)
    print(f"\nwrote      : {os.path.relpath(out, ROOT)}  ({written} strokes)")

    back = reader_to_ink(out)
    new = [s for p in back.pages for s in p.strokes]
    print(f"re-read    : {len(new)} strokes")
    drift = 0.0
    for s in page.strokes:
        match = min(new, key=lambda t: abs(t.bounds[0] - s.bounds[0])
                    + abs(t.bounds[1] - s.bounds[1]))
        drift = max(drift, max(abs(a - b) for a, b in zip(s.bounds, match.bounds)))
    print(f"drift      : {drift:.4f} pt worst-case through write+read")
    print("\nImport it and compare against the PDF.")


if __name__ == "__main__":
    main()
